spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}AQAkkE4wwGuMS6QHGu05zZ2Ouvx9p0RQValYKZUPfzsf8hYd3ZbyMJazi4nfJ+hwFhaCKmklIyBCNdz35Ziu8hhYY8+5XsvIxcY4IOHcMvgzK74gMkIeEMiN5xJNs2h1a9KTqaeFobdEQmR7ipa57nJ2O4brfHj2bR9rhq3p+cPPdVbX/M6WIRXkez274hDTrDaMb4iX+QX/2W4n5WKNifgJX9oK+wJLf94SNdvRcu0V/yJA+WkV+JNky3Mj326I/bqjM2v31Qm3yWs/En7DKA1AxtXJMKPuyB1PD41JHaFbErRx+gB8++HXKwUz3jYEX1mUc8D7xm5/gVf9JLUQi8qHfvgXgq9/pI71F9cIDzPL3PIpkxsrcFg38diCcVjWF+o='

jwt:
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9==userService
  token_expiration_time: 8640000000

gateway:
  ip: 172.18.0.5

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
